server:
  port: 9091
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: inventory_route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
        - id: billing_route
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka